import React from 'react'

export default function TermsPage() {
    return (
        <div className="mx-auto max-w-4xl px-6 py-12 md:py-20 text-tera-primary bg-tera-bg min-h-screen">
            <h1 className="mb-8 text-4xl font-bold tracking-tight text-tera-neon">Terms and Conditions</h1>
            <div className="prose max-w-none space-y-8 text-tera-secondary">
                <p className="text-lg leading-relaxed">
                    Welcome to Tera. By accessing or using our website and services, you agree to be bound by these Terms and Conditions.
                </p>

                <section>
                    <h2 className="mb-4 text-2xl font-semibold text-tera-primary">1. Acceptance of Terms</h2>
                    <p>
                        By creating an account or using Tera, you agree to comply with these terms. If you do not agree, you may not use our services.
                    </p>
                </section>

                <section>
                    <h2 className="mb-4 text-2xl font-semibold text-tera-primary">2. Description of Service</h2>
                    <p>
                        Tera is your AI Learning Companion — designed to help you learn anything as simply as possible. The services are provided "as is" and may change over time.
                    </p>
                </section>

                <section>
                    <h2 className="mb-4 text-2xl font-semibold text-white">3. User Conduct</h2>
                    <p>You agree not to:</p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>Use the service for any illegal or unauthorized purpose.</li>
                        <li>Attempt to bypass or hack our security measures.</li>
                        <li>Generate content that is harmful, abusive, or violates the rights of others.</li>
                        <li>Share your account credentials with others.</li>
                    </ul>
                </section>

                <section>
                    <h2 className="mb-4 text-2xl font-semibold text-white">4. AI Disclaimer</h2>
                    <p>
                        Tera uses advanced artificial intelligence to generate content. While we strive for accuracy, AI can make mistakes. You are responsible for reviewing and verifying any content generated by Tera before using it in a professional or educational setting. We are not liable for any errors or omissions in the generated content.
                    </p>
                </section>

                <section>
                    <h2 className="mb-4 text-2xl font-semibold text-white">5. Intellectual Property</h2>
                    <p>
                        You retain ownership of the content you input and the specific output generated for you, subject to these terms. Tera retains all rights to the underlying software, algorithms, and design.
                    </p>
                </section>

                <section>
                    <h2 className="mb-4 text-2xl font-semibold text-white">6. Termination</h2>
                    <p>
                        We reserve the right to suspend or terminate your account at our discretion if you violate these terms or for any other reason.
                    </p>
                </section>

                <section>
                    <h2 className="mb-4 text-2xl font-semibold text-white">7. Changes to Terms</h2>
                    <p>
                        We may update these terms from time to time. We will notify you of any significant changes. Your continued use of the service constitutes acceptance of the new terms.
                    </p>
                </section>

                <p className="text-sm text-white/50 mt-12">
                    Last updated: {new Date().toLocaleDateString()}
                </p>
            </div>
        </div>
    )
}
